sudo: required

language: elixir
elixir:
  - 1.3.0
  - 1.4.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:openjdk-r/ppa'
    packages:
      - openjdk-7-jdk
      - openjdk-8-jdk

env:
  matrix:
    - ES_VERSION=2.1.1 ES_PACKAGE_URL=https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.1.1/elasticsearch-2.1.1.deb J_NAME=java-1.7.0-openjdk-amd64 J_HOME=/usr/lib/jvm/java-1.7.0-openjdk-amd64
    - ES_VERSION=5.0.2 ES_PACKAGE_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.0.2.deb J_NAME=java-1.8.0-openjdk-amd64 J_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

before_install:
  - wget -O elasticsearch.deb "$ES_PACKAGE_URL"
  - sudo update-java-alternatives --set "$J_NAME"
  - export JAVA_HOME="$J_HOME"
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo service elasticsearch start

notifications:
  email: false
  slack:
    rooms:
      - zatvobor:eLjCTZD2l85xl19hsSdxkMdN##oss-feed
    on_success: change
